### ISSUE TITLE
Simplify first run procedure

### ISSUE THREAD

**Issue by pospi** [neighbour-hoods/applet-template#2]
`we-applet` defines the dependency `"@neighbourhoods/provider-applet": "file:../ui"`. Typescript doesn't seem to know how to deal with this-

```
[nix-shell:~/projects/neighbourhoods/timetracking-applet/we-ap
plet]$ npx tsc
src/index.ts:12:31 - error TS2307: Cannot find module '@neighbourhoods/provider-applet' or its corresponding type declarations.

12 import { ProviderStore } from "@neighbourhoods/provider-applet";
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/provider-applet.ts:6:44 - error TS2307: Cannot find module '@neighbourhoods/provider-applet' or its corresponding type declarations.

6 import { ProviderApp, ProviderStore } from "@neighbourhoods/provider-applet";
                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 2 errors in 2 files.

Errors  Files
     1  src/index.ts:12
     1  src/provider-applet.ts:6
```

I'm sure there's a loader for it that just needs to be configured (Node itself supports this, after all); but haven't figured it out yet. Logging here in case anybody knows the fix or if this is a non-critical error.

**Comment by julioholon** [comment]
@weswalla can you take a look? It seems this `provider-appet` module should not be inside @neighbourhoods, as it belongs to the very applet, no?

**Comment by pospi** [comment]
Thanks for this! Changed the issue title to reflect what's going on for me.

I do think that some instructions in the README about what's unimplemented in `ui` should be present- either that or the addition of some stub components so that it will compile on first run.

I think it would also be good to run `download-sensemaker` as a `postinstall` or `preinstall` script so that it automatically gets added to the workdir at setup time (I haven't seen that script triggered anywhere). We can probably also get rid of the `rimraf` and have a separate `clean` script which resets the repo to its original state (wiping these artifacts as well as other hApp build artifacts and all `node_modules` directories in the workspace). This would mean you can re-run installation easily if necessary, without having to redownload the same data.

I'm going to investigate dependencies but it does seem like there are some unrelated compile errors- I may need to update the Holochain client libs to be compatible with the beta RC2?

```
[nix-shell:~/projects/neighbourhoods/timetracking-applet]$ npm run start -w ui

> @neighbourhoods/provider-applet@0.0.0 start
> tsc && concurrently -r "npm run build:watch" "wds"

src/components/provider-component.ts:8:26 - error TS2307: Cannot find module './list-item' or its corresponding type declarations.

8 import { ListItem } from "./list-item";
                           ~~~~~~~~~~~~~

src/components/provider-component.ts:9:25 - error TS2307: Cannot find module './add-item' or its corresponding type declarations.

9 import { AddItem } from "./add-item";
                          ~~~~~~~~~~~~

src/provider-app-test-harness.ts:135:48 - error TS2345: Argument of type 'Promise<Uint8Array[]>' is not assignable to parameter of type 'Readable<unknown>'.
  Property 'subscribe' is missing in type 'Promise<Uint8Array[]>' but required in type 'Readable<unknown>'.

135     const allProviderResourceEntryHashes = get(this._providerStore.allProviderResourceEntryHashes())
                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  ../node_modules/svelte/types/runtime/store/index.d.ts:19:5
    19     subscribe(this: void, run: Subscriber<T>, invalidate?: Invalidator<T>): Unsubscriber;
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    'subscribe' is declared here.

src/provider-app-test-harness.ts:137:26 - error TS2304: Cannot find name 'allTaskEntryHashes'.

137     for (const taskEh of allTaskEntryHashes) {
                             ~~~~~~~~~~~~~~~~~~

src/provider-app.ts:41:25 - error TS2345: Argument of type 'Promise<Uint8Array[]>' is not assignable to parameter of type 'Readable<Uint8Array[]>'.
  Property 'subscribe' is missing in type 'Promise<Uint8Array[]>' but required in type 'Readable<Uint8Array[]>'.

41       resource_ehs: get(this.providerStore.allProviderResourceEntryHashes()),
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  ../node_modules/svelte/types/runtime/store/index.d.ts:19:5
    19     subscribe(this: void, run: Subscriber<T>, invalidate?: Invalidator<T>): Unsubscriber;
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    'subscribe' is declared here.

src/provider-store.ts:37:5 - error TS2322: Type 'string[]' is not assignable to type 'Uint8Array[]'.
  Type 'string' is not assignable to type 'Uint8Array'.

37     return this.service.allProviderResourceEntryHashes();
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 6 errors in 4 files.

Errors  Files
     2  src/components/provider-component.ts:8
     2  src/provider-app-test-harness.ts:135
     1  src/provider-app.ts:41
     1  src/provider-store.ts:37
```

**Comment by pospi** [comment]
BTW let me know if you want me to action any of the above myself, happy to send PRs

**Comment by pospi** [comment]
@weswalla 

> you will need to build the ts files in `./ui` first (`cd ui && npm run build`), then probably run `npm i`

Should the `package` script be updated to include this step? If it were `npm run build:happ && npm run build -w ui && npm run package:ui -w we-applet && hc web-app pack workdir` I would have thought that would be a complete build? Unless other scripts need to omit that step and do it separately elsewhere, of course...

**Comment by weswalla** [comment]
@pospi 

Just pushed a commit fixing those broken imports and types (a result of my sloppy translation from the todo-applet to a template): https://github.com/neighbour-hoods/applet-template/commit/cc53671afdc3795483c37bc9af72b5844a273929

> I think it would also be good to run download-sensemaker as a postinstall or preinstall script so that it automatically gets added to the workdir at setup time (I haven't seen that script triggered anywhere). We can probably also get rid of the rimraf and have a separate clean script which resets the repo to its original state (wiping these artifacts as well as other hApp build artifacts and all node_modules directories in the workspace). This would mean you can re-run installation easily if necessary, without having to redownload the same data.

> BTW let me know if you want me to action any of the above myself, happy to send PRs

That would be great! And all your suggestions are great :)

> Should the package script be updated to include this step? If it were npm run build:happ && npm run build -w ui && npm run package:ui -w we-applet && hc web-app pack workdir I would have thought that would be a complete build? Unless other scripts need to omit that step and do it separately elsewhere, of course...

yes, I think that would do it.
