### ISSUE TITLE
Pre-warm Cell WASMs to workaround long first request time

### ISSUE THREAD

**Issue by pospi** [neighbour-hoods/applet-template#24]
If our initialisation code was to call some non-existent zome method against all detected cells when initing it would speed up the first *actual* requests considerably when they happen later.

We should probably also assess the need for this in a "real" running We environment vs the `provider-app-test-harness.ts`; and place the warmup in the appropriate location if it is only necessary in particular contexts.

**Comment by weswalla** [comment]
Any examples of this elsewhere? Curious how it would speed up the first request, too!

**Comment by pospi** [comment]
Examples of what sorry?

First request gets sped up since a cold conductor has to first load in the WASM code for each requested zome from disk into the WASM virtual machine. For the Sensemaker that's probably a minor issue since the DNA file is only about 2MB; at 17MB the wait on the hREA Observation DNA is a little more jarring.

So ummm hmm what I'm hearing here is that this hasn't been a major performance implication for developers as yet.

**Comment by pospi** [comment]
Ok, the verdict is don't do this. Holochain can spike above 60% of CPU resources (which means 5+ cores on an 8-core machine) if you ask it to load up a bunch of WASMs all at once, which can in turn make the Sensemaker cell cloning time out (even with a 60s wait). Better to load them on demand and deal with the smaller waits as they come.
