### ISSUE TITLE
determine role of WDS in development pipeline

### ISSUE THREAD

**Issue by weswalla** [neighbour-hoods/applet-template#9]
> If we are going to modify our development pipeline to remove wds from the picture, then we should make that decision carefully and clean up after ourselves.
> 
> Are we sure? Granted, the build pipeline differences have been problematic. WDS does however make claims about its superior speed, we might be slowing things down dramatically by switching to Rollup. But maybe that is fine in the interests of "get it working" and we can revisit WDS later if we start getting reports about slow build speed?
> Something else to check: removing WDS means removing the ability to debug in any context other than a Tauri window, which means foregoing Firefox Devtools features and other development tooling plugins. The only way to debug elsewhere is via WDS or similar.
https://github.com/neighbour-hoods/applet-template/pull/7#issuecomment-1405999532

> Thinking about it more and bypassing WDS may also mean breaking HMR which is really going to slow down development a lot; would you mind testing with your working app to see if you can successfully hot-swap a component? If that's not working then I think we should put some time into getting WDS working again and run hc launch pointed at a URL rather than a file so that a HMR-capable dev env can run through it.
https://github.com/neighbour-hoods/applet-template/pull/7#issuecomment-1406021529

**Comment by pospi** [comment]
FWIW my rebuild time is just over 10 seconds with a one-component app, so I think we better revisit this soon :grimacing:

**Comment by pospi** [comment]
Well, I made some good progress on this today but got stuck on some buggy support between Rollup & Web Dev Server. I can see why this was all wired up in the less-than-optimal way that it was...

https://github.com/modernweb-dev/web/issues/1700#issuecomment-1137106493 is exactly what I'm encountering.
Possibly related to https://github.com/open-wc/open-wc/issues/2504; and to https://github.com/rollup/rollup/issues/3642 when using older versions.

Looks like the fix may be coming in the next release, so will park this until that happens.

**Comment by pospi** [comment]
It is worth noting that this is caused by the extremely-old package `tweetnacl` being referenced in the Holochain launcher. I don't know if a more modern repackaging of that library (eg. `tweetnacl-ts`) might fix things, but could be worth considering swapping it out.

**Comment by pospi** [comment]
Role determined: none. We are phasing this out in favour of a Vite-based build pipeline.
